In [1]:
import pandas as pd
iris = "E:\IRIS.csv"
ir = pd.read_csv(iris)
ir.head(10)



<div>
<style scoped>
    .dataframe tbody tr th:only-of-type {
        vertical-align: middle;
    }

    .dataframe tbody tr th {
        vertical-align: top;
    }

    .dataframe thead th {
        text-align: right;
    }
</style>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>5.1</th>
      <th>0.222222222</th>
      <th>3.5</th>
      <th>0.625</th>
      <th>1.4</th>
      <th>0.06779661</th>
      <th>0.2</th>
      <th>0.041666667</th>
      <th>setosa</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>4.9</td>
      <td>0.166667</td>
      <td>3.0</td>
      <td>0.416667</td>
      <td>1.4</td>
      <td>0.067797</td>
      <td>0.2</td>
      <td>0.041667</td>
      <td>setosa</td>
    </tr>
    <tr>
      <th>1</th>
      <td>4.7</td>
      <td>0.111111</td>
      <td>3.2</td>
      <td>0.500000</td>
      <td>1.3</td>
      <td>0.050847</td>
      <td>0.2</td>
      <td>0.041667</td>
      <td>setosa</td>
    </tr>
    <tr>
      <th>2</th>
      <td>4.6</td>
      <td>0.083333</td>
      <td>3.1</td>
      <td>0.458333</td>
      <td>1.5</td>
      <td>0.084746</td>
      <td>0.2</td>
      <td>0.041667</td>
      <td>setosa</td>
    </tr>
    <tr>
      <th>3</th>
      <td>5.0</td>
      <td>0.194444</td>
      <td>3.6</td>
      <td>0.666667</td>
      <td>1.4</td>
      <td>0.067797</td>
      <td>0.2</td>
      <td>0.041667</td>
      <td>setosa</td>
    </tr>
    <tr>
      <th>4</th>
      <td>5.4</td>
      <td>0.305556</td>
      <td>3.9</td>
      <td>0.791667</td>
      <td>1.7</td>
      <td>0.118644</td>
      <td>0.4</td>
      <td>0.125000</td>
      <td>setosa</td>
    </tr>
    <tr>
      <th>5</th>
      <td>4.6</td>
      <td>0.083333</td>
      <td>3.4</td>
      <td>0.583333</td>
      <td>1.4</td>
      <td>0.067797</td>
      <td>0.3</td>
      <td>0.083333</td>
      <td>setosa</td>
    </tr>
    <tr>
      <th>6</th>
      <td>5.0</td>
      <td>0.194444</td>
      <td>3.4</td>
      <td>0.583333</td>
      <td>1.5</td>
      <td>0.084746</td>
      <td>0.2</td>
      <td>0.041667</td>
      <td>setosa</td>
    </tr>
    <tr>
      <th>7</th>
      <td>4.4</td>
      <td>0.027778</td>
      <td>2.9</td>
      <td>0.375000</td>
      <td>1.4</td>
      <td>0.067797</td>
      <td>0.2</td>
      <td>0.041667</td>
      <td>setosa</td>
    </tr>
    <tr>
      <th>8</th>
      <td>4.9</td>
      <td>0.166667</td>
      <td>3.1</td>
      <td>0.458333</td>
      <td>1.5</td>
      <td>0.084746</td>
      <td>0.1</td>
      <td>0.010000</td>
      <td>setosa</td>
    </tr>
    <tr>
      <th>9</th>
      <td>5.4</td>
      <td>0.305556</td>
      <td>3.7</td>
      <td>0.708333</td>
      <td>1.5</td>
      <td>0.084746</td>
      <td>0.2</td>
      <td>0.041667</td>
      <td>setosa</td>
    </tr>
  </tbody>
</table>
</div>

In [26]:
import pandas as pd
iris = "E:\IRIS.csv"
ir = pd.read_csv(iris)
ir.shape

(99, 9)

In [5]:
ir.to_csv("E:\iris2.csv",sep = ',',index = False)


PermissionError: [Errno 13] Permission denied: 'E:\\iris2.csv'

In [7]:
ir.to_csv("E:\iris2.csv",sep = ',',index = False)

In [3]:
import pandas as pd;
url = 'E:\iris2.csv'
df = pd.read_csv(url)
df.columns


Index(['5.1', '0.222222222', '3.5', '0.625', '1.4', '0.06779661', '0.2',
       '0.041666667', 'setosa'],
      dtype='object')

In [5]:
setn = [1,2,3,4,5,6,7,8,9,10]
setm = [2,3,4,5,6,7,8,9,10,11]
print(list(map(lambda x,y: x*y,setm,setn)))

[2, 6, 12, 20, 30, 42, 56, 72, 90, 110]


In [8]:
import numpy as np
mat = np.array([[1,2],[3,4]])
print(mat)
mat.T

[[1 2]
 [3 4]]


array([[1, 3],
       [2, 4]])

In [11]:
mat.resize(4,1)
print(mat)

[[1]
 [2]
 [3]
 [4]]


In [12]:
a = [1,2,3,4,5,6,7,8,9]
arr = [((x) / (x + 1)) for x in a]
print(arr)

[0.5, 0.6666666666666666, 0.75, 0.8, 0.8333333333333334, 0.8571428571428571, 0.875, 0.8888888888888888, 0.9]


In [14]:
sum = 0
sum = sum +  [x for x in a]
print(sum)

TypeError: unsupported operand type(s) for +: 'int' and 'list'

In [23]:
from __future__ import print_function
import os
import pandas as pd
import warnings
from sklearn.neighbors import KNeighborsClassifier

def accuracy(real, predict):
    return (sum(real == predict) /(real.shape[0]))


# Import the data using the file path
filepath = 'E:\Orange_Telecom_Churn_Data.csv'
data = pd.read_csv(filepath)

data.drop(['state', 'area_code', 'phone_number'], axis=1, inplace=True)

from sklearn.preprocessing import LabelBinarizer
lb = LabelBinarizer()

for col in ['intl_plan', 'voice_mail_plan', 'churned']:
    data[col] = lb.fit_transform(data[col])

# Mute the sklearn warning

warnings.filterwarnings('ignore', module='sklearn')

from sklearn.preprocessing import MinMaxScaler

msc = MinMaxScaler()

data = pd.DataFrame(msc.fit_transform(data),  # this is an np.array, not a dataframe.
                    columns=data.columns)
x_cols = [x for x in data.columns if x != 'churned']

# Split the data into two dataframes
X_data = data[x_cols]
y_data = data['churned']


knn = KNeighborsClassifier(n_neighbors=3)

knn = knn.fit(X_data, y_data)

y_pred = knn.predict(X_data)
print(accuracy(y_data, y_pred))


TypeError: 'int' object is not callable